### ISSUE TITLE
CLI version support for Mac and CLI shipment for linux

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#163]
Need to implement a makefile target that will

- [x] Build binary for mac with version support

- [x] Build binary for linux in addition to container image

- [ ] as part of circle ci push of a release build and publish the binaries

- [ ] Support for brew tap

- [ ] Documentation for brew tap

**Comment by ransomw1c** [comment]
`make build-datamon-binaries` outputs the files to upload in the github release web ui to `out/release`.

note that the mac build uses the internal go linker (the linker implemented in go), not the llvm stack present on the mac desktop, because the build occurs in docker.  the `build-datamon-mac` target exists in case it becomes desirable to use an external linker to build the mac binary.

**Comment by fredbi** [comment]
Released artifacts are:
- brew tap for mac & linux
- docker images (linux built, may be used on any host)
- binaries for linux & mac

considering this done now. Closing.
