### ISSUE TITLE
Document the process for cross container synchronization for FS readiness

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#174]
There needs to be 

- [ ] A clear definition of when the FS is read to be consumed as a side car path

- [ ] Documentation of what application developers need to do to correctly wait for the FS to be ready for IO.

**Comment by ransomw1c** [comment]
ideas here include

* using the OS to detect whether the specified directory is mounted (e.g. `mount` command with no parameters)
* writing a pid file to indicate doneness of various conditions internal to datamon process (e.g. filesystem is mounted)
* creating a mount before preparing the filesystem internally and blocking request until the filesystem is prepared (in order to allow the mount to occur sooner)
* downloading metadata separately from the mount command and/or in parallel

**Comment by ransomw1c** [comment]
after discussion with Gabe and Ritesh:

container-to-container coordination can be implemented via wrapper scripts in both the application container and the datamon sidecar, communicating via writes to a shared volume.

the application wrapper script should be generic across executables in the main container and implemented in shell.

the datamon wrapper is specific to the task of providing a filesystem on startup. uploading bundles on signal from the application wrapper, and signalling upload done back in order to allow the main container to exit.

**Comment by fredbi** [comment]
all doc in a rather good & up-to-date status now. Closing.
