### ISSUE TITLE
Rename bundle to commit.

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#40]
Rename bundle to commit which is easier to explain.

**Comment by kerneltime** [comment]
@ransomw1c @casualjim This is the time to do it, else we can close this.
Opinions? Comments?

**Comment by fredbi** [comment]
@kerneltime @ransomw1c -- This is a github issue cleaning sweep

I believe the term "bundle" did eventually stick. And yes, we spend much time explaining that this is a commit. On the other hand, it may be better not to stick too much to the git terminology, since datamon is _not_ about emulating git.
