### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by kerneltime** [oneconcern/datamon#87]
Add ability to attach labels to bundles. 
1. Contributor defined labels
2. Labels generate for every commit for ease of use. Example <dev name>-<an easy to type word>
The namespace for labels is scoped per repo basis.

**Comment by kerneltime** [comment]
@kerneltime to write a proposal for the functionality of label and how it will work for review.

**Comment by ransomw1c** [comment]
### notes from conversation

✨ what a label is: a label is a key-value map with
* keys ~ human-readable text
* vals ~ machine generated hashes

##### cli requirements

* add a `--label` flag to bundle upload operation 🌀 possibly with multiple, comma-separated values
* commands to set labels and list bundles
* download and mount by label

##### implementation details

* labels will exist in their own `storage.Store` (i.e. bucket in the case of GCS), and each label gets its own serialized entry (e.g. a `.json` file or otherwise -- not a directory as in the case of the extant GCS buckets)
* add additional function to `cmd/` `Run:` implementations -- or possibly `uploadBundleDescriptor` -- that does label uploading

**Comment by ransomw1c** [comment]
there's currently a bug on overwriting labels (using `bundle upload` or `label set` with an extant label) wherein

```
googleapi: Error 412: Precondition Failed, conditionNotMet
```

is the error reported out of the application.

**Comment by fredbi** [comment]
Labels now work fine.
